### PR TITLE
update contribution guidelines

### PR DESCRIPTION
**Pull request by JannisNe**
I do love the review workflow a lot. To document that somewhere also for potential new contributors I revamped the `CONTRIBUTING.md`. Let me know what you think.

### CODE REVIEW

**Review by robertdstein — CHANGES_REQUESTED** [review]
So I think we should be a bit clearer about a review policy. Specifically, I guess we would be in one of the following categories:

- Always required
- Always recommended
- Required for major changes only, optional otherwise
- Recommended for major changes only, optional otherwise

I would vote that we just state which of these guidelines we follow. 

Also, based on experience from other projects, I'd mention what is a reasonable wait time for review before you should feel empowered to chase up reviewers? Something like a week perhaps.

**Comment by robertdstein** [comment]
> Good point. As per review guideline, which one would you pick? I would think
> 
>     * Required for major changes only, optional otherwise
> 
> 
> sounds reasonable. One week for a reviewer to answer sounds good.

I agree "Required for major changes only, optional otherwise" sounds reasonable

**Review by robertdstein — CHANGES_REQUESTED** [review]
So one final change: I would say that minor changes do not need review but should still go via PR. That ensures everything committed has passed unit tests. Basically, I think we should avoid any commits directly to main, and should say so explicitly.

**Review by robertdstein — APPROVED** [review]

**Comment by mlincett** [comment]
Text looks nice, I did some proofreading.

About the reproducibility part, I would try to word it more carefully: on the long run, I do not think we want to store many (and possibly large) catalogues inside the flarestack repository - the AGN analysis takes 32 MiB of space already.

**Comment by mlincett** [comment]
> Well, we don't say explicitly that catalogues should be included.

Agree, but I'd rather be explicit against their inclusion in the repo :) I committed some changes to the text but feel free to amend.

**Review by mlincett — APPROVED** [review]

**Comment by JannisNe** [comment]
Looks good!

**Pull request merged**
