### PR TITLE
Define `catalogue_dtype` in `flarestack.core.data_types`

### LINKED ISSUE #175: Decouple `cat_dtype` from `flarestack__data`
The catalogue data type (`cat_dtype`) is currently part of `utils.prepare_catalogue.py`, that in turns imports from `flarestack.shared`, triggering the creation of the `flarestack__data` directory tree.

I would like to separate the definition of the catalogue data type in a separate module, so that importing `cat_dtype` is independent of `flarestack__data` and does not attempt to write to disk.

Such module could be called `data_types` and located in a directory of our choice (please advise!)

### PR DESCRIPTION
**Pull request by mlincett**
Closes #175 by introducing a `data_types` module in `flarestack.core`. 

The module `utils.prepare_catalogue` has been updated, but still imports it as `cat_dtype` so the old analysis scripts can still work.

References to the data type in the code have been updated.

### CODE REVIEW

**Review by JannisNe — COMMENTED** [review]
Looks nice!
I would suggest adding something about this in the docs.
At least include the module [here](https://github.com/icecube/flarestack/blob/8d9a584ef955c25c0ddb31ad7b6d0f5b56d10e7b/docs/source/api.rst) if not even add an extra chapter for the type. For that, you'd need to create a file (i.e. `dtype.rst`) in `docs/source/` and include it [here](https://github.com/icecube/flarestack/blob/8d9a584ef955c25c0ddb31ad7b6d0f5b56d10e7b/docs/source/index.rst#L46-48).

**Comment by mlincett** [comment]
> Looks nice! I would suggest adding something about this in the docs. At least include the module [here](https://github.com/icecube/flarestack/blob/8d9a584ef955c25c0ddb31ad7b6d0f5b56d10e7b/docs/source/api.rst) if not even add an extra chapter for the type. For that, you'd need to create a file (i.e. `dtype.rst`) in `docs/source/` and include it [here](https://github.com/icecube/flarestack/blob/8d9a584ef955c25c0ddb31ad7b6d0f5b56d10e7b/docs/source/index.rst#L46-48).

Fair point, thanks! It's done.

**Comment by JannisNe** [comment]
Nice!
I compiled the version of the docs [here](https://flarestack.readthedocs.io/en/data-type/) and it looks like the API part does not work somehow. I can look into it later but I don't have a good idea why that could be. `api.rst` looks right to me.

**Comment by mlincett** [comment]
> Nice! I compiled the version of the docs [here](https://flarestack.readthedocs.io/en/data-type/) and it looks like the API part does not work somehow. I can look into it later but I don't have a good idea why that could be. `api.rst` looks right to me.

I think there is no proper way to produce a docstring that would work for a single name / data type definition. Do you have some advice?

**Comment by mlincett** [comment]
> Ah true, you won't get variables from the `.. automodule::`. In that case I'd say we just drop it?

As in leave as it is or as in drop the automodule?

An alternative option would be to wrap the data type in a class.

**Comment by JannisNe** [comment]
As in drop it from `api.rst`. For now, I think wrapping it in a class would be a bit overkill if it's only to get the documentation.

**Comment by mlincett** [comment]
> As in drop it from `api.rst`. For now, I think wrapping it in a class would be a bit overkill if it's only to get the documentation.

Agreed. Please check again :)

**Pull request merged**
